package models

// Code generated by avro/gen. DO NOT EDIT.

// Alert is a generated struct.
type Alert struct {
	// The unique id that identifies the sensor.
	SensorID int64 `avro:"sensor_id" json:"sensor_id" yaml:"SensorId"`
	// Time the alert was generated as UTC milliseconds from the epoch.
	Time int64 `avro:"time" json:"time" yaml:"Time"`
	// The allowed values that our sensors will use to emit current status.
	Status string `avro:"status" json:"status" yaml:"Status"`
}
