// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     account.avsc
 *     funds.avsc
 *     transaction.avsc
 *     transaction_result.avsc
 */
package models

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type ErrorType int32

const (
	ErrorTypeINSUFFICIENT_FUNDS ErrorType = 0
)

func (e ErrorType) String() string {
	switch e {
	case ErrorTypeINSUFFICIENT_FUNDS:
		return "INSUFFICIENT_FUNDS"
	}
	return "unknown"
}

func writeErrorType(r ErrorType, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewErrorTypeValue(raw string) (r ErrorType, err error) {
	switch raw {
	case "INSUFFICIENT_FUNDS":
		return ErrorTypeINSUFFICIENT_FUNDS, nil
	}

	return -1, fmt.Errorf("invalid value for ErrorType: '%s'", raw)

}

func (b ErrorType) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *ErrorType) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewErrorTypeValue(stringVal)
	*b = val
	return err
}

type ErrorTypeWrapper struct {
	Target *ErrorType
}

func (b ErrorTypeWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b ErrorTypeWrapper) SetInt(v int32) {
	*(b.Target) = ErrorType(v)
}

func (b ErrorTypeWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b ErrorTypeWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b ErrorTypeWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b ErrorTypeWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b ErrorTypeWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b ErrorTypeWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b ErrorTypeWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b ErrorTypeWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b ErrorTypeWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b ErrorTypeWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b ErrorTypeWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b ErrorTypeWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b ErrorTypeWrapper) Finalize() {}
