// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     account.avsc
 *     funds.avsc
 *     transaction.avsc
 *     transaction_result.avsc
 */
package models

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type TransactionType int32

const (
	TransactionTypeDEPOSIT  TransactionType = 0
	TransactionTypeWITHDRAW TransactionType = 1
)

func (e TransactionType) String() string {
	switch e {
	case TransactionTypeDEPOSIT:
		return "DEPOSIT"
	case TransactionTypeWITHDRAW:
		return "WITHDRAW"
	}
	return "unknown"
}

func writeTransactionType(r TransactionType, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewTransactionTypeValue(raw string) (r TransactionType, err error) {
	switch raw {
	case "DEPOSIT":
		return TransactionTypeDEPOSIT, nil
	case "WITHDRAW":
		return TransactionTypeWITHDRAW, nil
	}

	return -1, fmt.Errorf("invalid value for TransactionType: '%s'", raw)

}

func (b TransactionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *TransactionType) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewTransactionTypeValue(stringVal)
	*b = val
	return err
}

type TransactionTypeWrapper struct {
	Target *TransactionType
}

func (b TransactionTypeWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b TransactionTypeWrapper) SetInt(v int32) {
	*(b.Target) = TransactionType(v)
}

func (b TransactionTypeWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b TransactionTypeWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b TransactionTypeWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b TransactionTypeWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b TransactionTypeWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b TransactionTypeWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b TransactionTypeWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b TransactionTypeWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b TransactionTypeWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b TransactionTypeWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b TransactionTypeWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b TransactionTypeWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b TransactionTypeWrapper) Finalize() {}
