// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     account.avsc
 *     funds.avsc
 *     transaction.avsc
 *     transaction_result.avsc
 */
package models

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullErrorTypeTypeEnum int

const (
	UnionNullErrorTypeTypeEnumErrorType UnionNullErrorTypeTypeEnum = 1
)

type UnionNullErrorType struct {
	Null      *types.NullVal
	ErrorType ErrorType
	UnionType UnionNullErrorTypeTypeEnum
}

func writeUnionNullErrorType(r *UnionNullErrorType, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullErrorTypeTypeEnumErrorType:
		return writeErrorType(r.ErrorType, w)
	}
	return fmt.Errorf("invalid value for *UnionNullErrorType")
}

func NewUnionNullErrorType() *UnionNullErrorType {
	return &UnionNullErrorType{}
}

func (r *UnionNullErrorType) Serialize(w io.Writer) error {
	return writeUnionNullErrorType(r, w)
}

func DeserializeUnionNullErrorType(r io.Reader) (*UnionNullErrorType, error) {
	t := NewUnionNullErrorType()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullErrorTypeFromSchema(r io.Reader, schema string) (*UnionNullErrorType, error) {
	t := NewUnionNullErrorType()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullErrorType) Schema() string {
	return "[\"null\",{\"name\":\"ErrorType\",\"symbols\":[\"INSUFFICIENT_FUNDS\"],\"type\":\"enum\"}]"
}

func (_ *UnionNullErrorType) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullErrorType) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullErrorType) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullErrorType) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullErrorType) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullErrorType) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullErrorType) SetLong(v int64) {

	r.UnionType = (UnionNullErrorTypeTypeEnum)(v)
}

func (r *UnionNullErrorType) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		return &ErrorTypeWrapper{Target: (&r.ErrorType)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullErrorType) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullErrorType) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullErrorType) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullErrorType) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullErrorType) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullErrorType) Finalize()                        {}

func (r *UnionNullErrorType) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullErrorTypeTypeEnumErrorType:
		return json.Marshal(map[string]interface{}{"org.kafkainaction.ErrorType": r.ErrorType})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullErrorType")
}

func (r *UnionNullErrorType) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["org.kafkainaction.ErrorType"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.ErrorType)
	}
	return fmt.Errorf("invalid value for *UnionNullErrorType")
}
